In [11]:
import os
os.environ["mode"] = 'dev'

In [12]:
import sys
sys.path.append(r'C:\Users\Mi\Desktop\code\git\python-utils-ak')
sys.path.append(r'C:\Users\Mi\Desktop\code\git\2020.10-umalat\umalat')
from utils_ak.interactive_imports import *

In [13]:
def _import_globals(module):
    for x in dir(module):
        if not x.startswith('_'):
            globals()[x] = getattr(module, x)
            
def _load(module_obj, module_name=None, reload=False, import_globals=False):
    module = load(module_obj, module_name, reload, import_globals=False)
    if import_globals:
        _import_globals(module)
    return module

def load_sources():
    _load(r'C:\Users\Mi\Desktop\code\git\2020.10-umalat\umalat\app\schedule_maker\utils/time.py', import_globals=True, reload=True)
    _load(r'C:\Users\Mi\Desktop\code\git\2020.10-umalat\umalat\app\schedule_maker\utils/block.py', import_globals=True, reload=True)
    _load(r'C:\Users\Mi\Desktop\code\git\2020.10-umalat\umalat\app\schedule_maker\utils/color.py', import_globals=True, reload=True)
    _load(r'C:\Users\Mi\Desktop\code\git\2020.10-umalat\umalat\app\schedule_maker\utils/drawing.py', import_globals=True, reload=True)
    _load(r'C:\Users\Mi\Desktop\code\git\2020.10-umalat\umalat\app\schedule_maker\utils/interval.py', import_globals=True, reload=True)
    
    _load(r'C:\Users\Mi\Desktop\code\git\2020.10-umalat\umalat\app\schedule_maker\blocks.py', import_globals=True, reload=True)

    _load(r'C:\Users\Mi\Desktop\code\git\2020.10-umalat\umalat\app\schedule_maker\models.py', import_globals=True, reload=True)
    _load(r'C:\Users\Mi\Desktop\code\git\2020.10-umalat\umalat\app\schedule_maker\algo.py', import_globals=True, reload=True)
    _load(r'C:\Users\Mi\Desktop\code\git\2020.10-umalat\umalat\app\schedule_maker\style.py', import_globals=True, reload=True)
    _load(r'C:\Users\Mi\Desktop\code\git\2020.10-umalat\umalat\app\schedule_maker\validation.py', import_globals=True, reload=True)
    _load(r'C:\Users\Mi\Desktop\code\git\2020.10-umalat\umalat\app\utils\openpyxl_wrapper.py', import_globals=True, reload=True)
#     _load(r'C:\Users\Mi\Desktop\code\git\2020.10-umalat\umalat\app\utils\excel_client.py', import_globals=True, reload=True)

load_sources()

In [14]:
fn = r"C:\Users\Mi\Desktop\umalat\2020 scheduling\2020\12. декабрь\04.12.20.xlsx"

In [15]:
date = cast_datetime(os.path.splitext(os.path.basename(fn))[0])
date

datetime.datetime(2020, 4, 12, 0, 0)

In [16]:
values = db.session.query(SKU).all()
skus = pd.DataFrame(values, columns=['sku'])
skus['name'] = skus['sku'].apply(lambda sku:sku.name)
skus.head()

       sku                                                            name
0  <SKU 1>  Моцарелла "Pretto" (для бутербродов), 45%, 0,2 кг, т/ф, (9 шт)
1  <SKU 2>                            Моцарелла "Pretto", 45%, 1,2 кг, в/у
2  <SKU 3>               Моцарелла "Unagrande", 45%, 0,12 кг, ф/п (кубики)
3  <SKU 4>                          Моцарелла "Unagrande", 45%, 3 кг, пл/л
4  <SKU 5>                              Моцарелла (палочки), 45%, кг, пл/л

In [17]:
values = db.session.query(SKU).all()
skus = pd.DataFrame(values, columns=['sku'])
skus['name'] = skus['sku'].apply(lambda sku:sku.name)
skus['percent'] = skus['sku'].apply(lambda sku:sku.boilings[0].percent)
skus.head()

,sku,name,percent
0,<SKU 1>,"Моцарелла ""Pretto"" (для бутербродов), 45%, 0,2 кг, т/ф, (9 шт)",2.7
1,<SKU 2>,"Моцарелла ""Pretto"", 45%, 1,2 кг, в/у",2.7
2,<SKU 3>,"Моцарелла ""Unagrande"", 45%, 0,12 кг, ф/п (кубики)",2.7
3,<SKU 4>,"Моцарелла ""Unagrande"", 45%, 3 кг, пл/л",2.7
4,<SKU 5>,"Моцарелла (палочки), 45%, кг, пл/л",2.7

In [18]:
values = db.session.query(Boiling).all()
boilings = pd.DataFrame(values, columns=['boiling'])
boilings['percent'] = boilings['boiling'].apply(lambda b: b.percent)
boilings

         boiling  percent
0    <Boiling 1>      2.7
1    <Boiling 2>      2.7
2    <Boiling 3>      2.7
3    <Boiling 4>      2.7
4    <Boiling 5>      3.3
5    <Boiling 6>      3.3
6    <Boiling 7>      3.3
7    <Boiling 8>      3.3
8    <Boiling 9>      3.6
9   <Boiling 10>      3.6
10  <Boiling 11>      3.6
11  <Boiling 12>      3.6

In [19]:
wb = openpyxl.load_workbook(filename=fn, data_only=True)
ws = wb['планирование суточное']
values = []
for i in range(1, 200):
    if ws.cell(i, 3).value:
        values.append([ws.cell(i, j).value for j in range(3, 7)])

In [20]:
df = pd.DataFrame(values[1:]) # first value is header
df = df.fillna(0)
df = df[df[3] != 0]
df.head()

,0,1,2,3
0,"Моцарелла Фиор ди латте в воде ""Unagrande"", 50%, 0,125 кг, ф/п, (8 шт)",-1713,0,-1713.0
1,"Моцарелла Грандиоза в воде ""Unagrande"", 50%, 0,2 кг, ф/п",-33.6,0,-33.6
4,"Моцарелла Фиор Ди Латте в воде ""Pretto"", 45%, 0,125 кг, ф/п, (8 шт)",-100,0,-100.0
5,"Моцарелла Фиор Ди Латте в воде ""Pretto"", 45%, 0,1 кг, ф/п, (8 шт)",-192.8,0,-192.8
6,"Моцарелла Фиор ди Латте в воде ""Ваш выбор"", 50%, 0,1 кг, ф/п",-140.4,0,-140.4

In [34]:
from app.schedule_maker.models import *
df['sku'] = df[0].apply(lambda obj: db.session.query(SKU).filter(SKU.name == obj).first())
df = df[~df['sku'].isnull()]
df['boiling_type'] = df['sku'].apply(lambda sku: ' '.join([str(sku.boilings[0].percent), str(sku.boilings[0].ferment)]))
df['form_factor'] = df['sku'].apply(lambda sku: sku.form_factor.name)
df['sample_boiling'] = df['sku'].apply(lambda sku: sku.boilings[0])
df['sample_boiling_id'] = df['sku'].apply(lambda sku: sku.boilings[0].id)
df['size'] = df['sku'].apply(lambda sku: sku.weight_form_factor)
df.head()

,0,1,2,3,sku,boiling_type,form_factor,sample_boiling,sample_boiling_id,size
0,"Моцарелла Фиор ди латте в воде ""Unagrande"", 50%, 0,125 кг, ф/п, (8 шт)",-1713,0,-1713.0,<SKU 25>,3.6 Альче,Фиор Ди Латте,<Boiling 9>,9,125.0
1,"Моцарелла Грандиоза в воде ""Unagrande"", 50%, 0,2 кг, ф/п",-33.6,0,-33.6,<SKU 12>,3.6 Альче,Фиор Ди Латте,<Boiling 9>,9,200.0
4,"Моцарелла Фиор Ди Латте в воде ""Pretto"", 45%, 0,125 кг, ф/п, (8 шт)",-100,0,-100.0,<SKU 24>,3.3 Сакко,Фиор Ди Латте,<Boiling 6>,6,125.0
5,"Моцарелла Фиор Ди Латте в воде ""Pretto"", 45%, 0,1 кг, ф/п, (8 шт)",-192.8,0,-192.8,<SKU 23>,3.3 Сакко,Фиор Ди Латте,<Boiling 6>,6,100.0
6,"Моцарелла Фиор ди Латте в воде ""Ваш выбор"", 50%, 0,1 кг, ф/п",-140.4,0,-140.4,<SKU 26>,3.3 Сакко,Фиор Ди Латте,<Boiling 6>,6,100.0

In [43]:
# generate js
js = {'Date': date, 'WeekDay': date.weekday(), 'Boilings': []} 

for ff, ff_grp in df[df[3] != 0].groupby('boiling_type'):
    
    for i, (b, b_grp) in enumerate(ff_grp.groupby('sample_boiling_id')):
        df1 = b_grp.sort_values(by='size', ascending=False)
        values = {}
        for i, row in df1.iterrows():
            values[row['sku'].id] = abs(row[3])
        
        boiling_count = sum(values.values()) / 850 if '2.7' in row['boiling_type'] else sum(values.values()) / 1000
        boiling_count = math.ceil(boiling_count)
        
        js['Boilings'].append({'BoilingId': row['sample_boiling_id'],
                              'BoilingCount': boiling_count, 
                            'BoilingCountFactual': boiling_count,
                              'SKUVolumes': values,
                              'BoilingType': row['boiling_type'],
                              'TotalVolume': sum(values.values())})

In [49]:
pyperclip.copy(cast_js(js, indent=1))